/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room.glb 
*/

import React, { useRef, useMemo } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import { EffectComposer, SelectiveBloom } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";
import * as THREE from "three";

export function Room({ optimized = false }) {
  const { nodes, materials } = useGLTF("/models/optimized-room.glb");
  const screensRef = useRef();
  const matcapTexture = useTexture("/images/textures/mat1.png");

  // Usamos useMemo para crear materiales solo una vez
  const memoizedMaterials = useMemo(() => {
    // Reducir calidad de materiales en modo optimizado
    const phongSettings = optimized ? { shininess: 10, flatShading: true } : { shininess: 30 };
    const standardSettings = optimized ? { roughness: 0.8, metalness: 0.1 } : { roughness: 0.3, metalness: 0.5 };
    
    return {
      curtainMaterial: new THREE.MeshPhongMaterial({
        color: "#d90429",
        ...phongSettings
      }),

      bodyMaterial: new THREE.MeshPhongMaterial({
        map: matcapTexture,
        ...phongSettings
      }),

      tableMaterial: new THREE.MeshPhongMaterial({
        color: "#582f0e",
        ...phongSettings
      }),

      radiatorMaterial: new THREE.MeshPhongMaterial({
        color: "#fff",
        ...phongSettings
      }),

      compMaterial: optimized ? 
        new THREE.MeshPhongMaterial({
          color: "#fff",
          ...phongSettings
        }) : 
        new THREE.MeshStandardMaterial({
          color: "#fff",
          ...standardSettings
        }),

      pillowMaterial: new THREE.MeshPhongMaterial({
        color: "#8338ec",
        ...phongSettings
      }),

      chairMaterial: new THREE.MeshPhongMaterial({
        color: "#000",
        ...phongSettings
      }),

      glassMaterial: optimized ?
        new THREE.MeshPhongMaterial({
          color: "#88ccff",
          transparent: true,
          opacity: 0.4,
        }) :
        new THREE.MeshPhysicalMaterial({
          color: "#88ccff",
          transparent: true,
          opacity: 0.4,
          roughness: 0.1,
          transmission: 0.9,
          reflectivity: 0.5,
        })
    };
  }, [matcapTexture, optimized]);
  return (
    <group dispose={null}>
      {/* Solo añadir efectos si no estamos en modo optimizado */}
      {!optimized && (
        <EffectComposer enabled={!optimized}>
          <SelectiveBloom
            selection={screensRef}
            intensity={1.5}
            luminanceThreshold={0.2}
            luminanceSmoothing={0.9}
            blendFunction={BlendFunction.ADD}
          />
        </EffectComposer>
      )}
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={memoizedMaterials.curtainMaterial}
      />
      <mesh geometry={nodes.body1_blinn1_0.geometry} material={memoizedMaterials.bodyMaterial} />
      <mesh geometry={nodes.cabin_blinn1_0.geometry} material={memoizedMaterials.tableMaterial} />
      <mesh
        geometry={nodes.chair_body_blinn1_0.geometry}
        material={memoizedMaterials.chairMaterial}
      />
      <mesh geometry={nodes.comp_blinn1_0.geometry} material={memoizedMaterials.compMaterial} />
      <mesh
        ref={screensRef}
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.handls_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.keyboard_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.kovrik_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_bl_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.lamp_white_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.miuse_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor2_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.monitor3_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.pCylinder5_blinn1_0.geometry}
        material={materials.blinn1}
      />      <mesh
        geometry={nodes.pillows_blinn1_0.geometry}
        material={memoizedMaterials.pillowMaterial}
      />
      <mesh
        geometry={nodes.polySurface53_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0.geometry}
        material={memoizedMaterials.radiatorMaterial}
      />
      <mesh
        geometry={nodes.radiator_blinn1_0001.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.railing_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_bttns_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.red_vac_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.stylus_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh geometry={nodes.table_blinn1_0.geometry} material={memoizedMaterials.tableMaterial} />
      <mesh
        geometry={nodes.tablet_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.triangle_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vac_black_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuum1_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vacuumgrey_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.vires_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.window_blinn1_0.geometry}
        material={materials.blinn1}
      />      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={memoizedMaterials.glassMaterial}
      />
    </group>
  );
}

useGLTF.preload("/models/optimized-room.glb");
